In [1]:
import os

for f in sorted(os.listdir("../data/raw/")):
    print(f)

.gitkeep
HMP2_metadata.csv
HMP2_taxonomic_profiles.tsv.gz
podlesny2022_abundance.xlsx
podlesny2022_metadata.xlsx
smillie_feature_AUC_table.xlsx
smillie_fmt_abundances.xlsx
smillie_species_name_map.xlsx

In [3]:
import pandas as pd

def smart_load(path, nrows=3):
    ext = path.split('.')[-1].lower()
    
    if ext == 'gz':
        df = pd.read_csv(path, sep='\t', compression='gzip', nrows=nrows)
    elif ext == 'tsv':
        df = pd.read_csv(path, sep='\t', nrows=nrows)
    elif ext == 'csv':
        df = pd.read_csv(path, nrows=nrows)
    elif ext == 'xlsx':
        df = pd.read_excel(path, nrows=nrows)
    else:
        print("Unknown file type:", path)
        return None
    
    print("Loaded:", path)
    print(df.head())
    print("-" * 40)
    return df

In [4]:
smart_load("../data/raw/podlesny2022_metadata.xlsx")

Loaded: ../data/raw/podlesny2022_metadata.xlsx
        Manuscript Study Disease_Group Disease       Case_Name        Name  \
0  Podlesny et al.   FRI          rCDI    rCDI  FRICKE_Case_16  FRICKE_16A
1  Podlesny et al.   FRI          rCDI    rCDI  FRICKE_Case_18  FRICKE_18A
2  Podlesny et al.   FRI          rCDI    rCDI  FRICKE_Case_19  FRICKE_19A

   Donor.Name   Sample_Type  Days_Since_FMT         Case_ABx  ABx_days  \
0  FRICKE_16B  Pre Post-ABx               0              NaN       NaN
1  FRICKE_18B  Pre Post-ABx               0  fluoroquinolone       NaN
2  FRICKE_19B  Pre Post-ABx               0              NaN       NaN

   ABx_PostFMT  Lavage  FMT_route  FMT_rounds  Colonoscopy_n  Nasogastric_n  \
0          NaN       0        NaN           0              0              0
1          NaN       0        NaN           0              0              0
2          NaN       0        NaN           0              0              0

   Gastroduodenal_n  Enema_n  Pill_n
0                 0        0       0
1                 0        0       0
2                 0        0       0
----------------------------------------

,Manuscript,Study,Disease_Group,Disease,Case_Name,Name,Donor.Name,Sample_Type,Days_Since_FMT,Case_ABx,ABx_days,ABx_PostFMT,Lavage,FMT_route,FMT_rounds,Colonoscopy_n,Nasogastric_n,Gastroduodenal_n,Enema_n,Pill_n
0,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_16,FRICKE_16A,FRICKE_16B,Pre Post-ABx,0,NaN,NaN,NaN,0,NaN,0,0,0,0,0,0
1,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_18,FRICKE_18A,FRICKE_18B,Pre Post-ABx,0,fluoroquinolone,NaN,NaN,0,NaN,0,0,0,0,0,0
2,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_19,FRICKE_19A,FRICKE_19B,Pre Post-ABx,0,NaN,NaN,NaN,0,NaN,0,0,0,0,0,0

In [5]:
pod = pd.read_excel("../data/raw/podlesny2022_metadata.xlsx")

pod[['FMT_rounds', 'Colonoscopy_n', 'Enema_n', 'Pill_n']].describe()

        FMT_rounds  Colonoscopy_n      Enema_n       Pill_n
count  1171.000000    1171.000000  1171.000000  1171.000000
mean      5.647310       0.487617     4.491887     2.847993
std      11.761277       0.859621    11.896012     8.214795
min       0.000000       0.000000     0.000000     0.000000
25%       0.000000       0.000000     0.000000     0.000000
50%       1.000000       0.000000     0.000000     0.000000
75%       2.000000       1.000000     0.000000     0.000000
max      41.000000       5.000000    40.000000    28.000000

In [6]:
pod.dtypes

Manuscript           object
Study                object
Disease_Group        object
Disease              object
Case_Name            object
Name                 object
Donor.Name           object
Sample_Type          object
Days_Since_FMT      float64
Case_ABx             object
ABx_days            float64
ABx_PostFMT         float64
Lavage              float64
FMT_route            object
FMT_rounds          float64
Colonoscopy_n       float64
Nasogastric_n       float64
Gastroduodenal_n    float64
Enema_n             float64
Pill_n              float64
dtype: object

In [8]:
pod.isna().sum().sort_values(ascending=False)

Case_ABx            1079
ABx_PostFMT          590
FMT_route            588
Donor.Name           433
ABx_days             307
Case_Name            297
Days_Since_FMT       297
Disease              297
Nasogastric_n        245
Gastroduodenal_n     245
FMT_rounds           245
Lavage               245
Enema_n              245
Pill_n               245
Colonoscopy_n        245
Manuscript             0
Disease_Group          0
Study                  0
Name                   0
Sample_Type            0
dtype: int64

In [9]:
pod[['Case_Name', 'Sample_Type', 'Days_Since_FMT']].head()

        Case_Name   Sample_Type  Days_Since_FMT
0  FRICKE_Case_16  Pre Post-ABx             0.0
1  FRICKE_Case_18  Pre Post-ABx             0.0
2  FRICKE_Case_19  Pre Post-ABx             0.0
3  FRICKE_Case_20  Pre Post-ABx             0.0
4  FRICKE_Case_23  Pre Post-ABx             0.0

In [10]:
abund = pd.read_excel("../data/raw/podlesny2022_abundance.xlsx")
abund.head()

   Name                            species  rel_abund
0  FMT1              Bacteroides_stercoris   0.275204
1  FMT1              Bacteroides_uniformis   0.094942
2  FMT1                  Bacteroides_dorei   0.089475
3  FMT1  Bifidobacterium_pseudocatenulatum   0.084323
4  FMT1       Faecalibacterium_prausnitzii   0.042626

In [11]:
abund_wide = abund.pivot_table(
    index="Name",
    columns="species",
    values="rel_abund",
    fill_value=0
)

abund_wide.head()

species,Abiotrophia_defectiva,Abiotrophia_sp_HMSC24B09,Absiella_dolichum,Achromobacter_xylosoxidans,Acidaminococcus_fermentans,Acidaminococcus_intestini,Acidaminococcus_sp_CAG_542,Acinetobacter_baumannii,Acinetobacter_johnsonii,Acinetobacter_nosocomialis,...,Weissella_halotolerans,Weissella_jogaejeotgali,Weissella_koreensis,Weissella_minor,Weissella_paramesenteroides,Weissella_thailandensis,Weissella_viridescens,Xanthomonas_fragariae,Yersinia_entomophaga,[Collinsella]_massiliensis
Name,,,,,,,,,,,,,,,,,,,,,
1_15_D0,0.0,0.0,0.000676,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000016
1_15_W10,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1_15_W18,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1_15_W2,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000055
1_15_W24,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000055

In [12]:
abund_wide.index[:10]

Index(['1_15_D0', '1_15_W10', '1_15_W18', '1_15_W2', '1_15_W24', '1_15_W6',
       '1_17_D0', '1_17_W10', '1_17_W2', '1_17_W6'],
      dtype='object', name='Name')

In [14]:
pod_meta = pd.read_excel("../data/raw/podlesny2022_metadata.xlsx")
pod_meta.head()

,Manuscript,Study,Disease_Group,Disease,Case_Name,Name,Donor.Name,Sample_Type,Days_Since_FMT,Case_ABx,ABx_days,ABx_PostFMT,Lavage,FMT_route,FMT_rounds,Colonoscopy_n,Nasogastric_n,Gastroduodenal_n,Enema_n,Pill_n
0,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_16,FRICKE_16A,FRICKE_16B,Pre Post-ABx,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_18,FRICKE_18A,FRICKE_18B,Pre Post-ABx,0.0,fluoroquinolone,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
2,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_19,FRICKE_19A,FRICKE_19B,Pre Post-ABx,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
3,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_20,FRICKE_20A,FRICKE_20B,Pre Post-ABx,0.0,"lincosamide, fluoroquinolone",NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
4,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_23,FRICKE_23A,FRICKE_23B,Pre Post-ABx,0.0,lincosamide,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
pod_meta.columns

Index(['Manuscript', 'Study', 'Disease_Group', 'Disease', 'Case_Name', 'Name',
       'Donor.Name', 'Sample_Type', 'Days_Since_FMT', 'Case_ABx', 'ABx_days',
       'ABx_PostFMT', 'Lavage', 'FMT_route', 'FMT_rounds', 'Colonoscopy_n',
       'Nasogastric_n', 'Gastroduodenal_n', 'Enema_n', 'Pill_n'],
      dtype='object')

In [16]:
pod_meta.head(3)

,Manuscript,Study,Disease_Group,Disease,Case_Name,Name,Donor.Name,Sample_Type,Days_Since_FMT,Case_ABx,ABx_days,ABx_PostFMT,Lavage,FMT_route,FMT_rounds,Colonoscopy_n,Nasogastric_n,Gastroduodenal_n,Enema_n,Pill_n
0,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_16,FRICKE_16A,FRICKE_16B,Pre Post-ABx,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_18,FRICKE_18A,FRICKE_18B,Pre Post-ABx,0.0,fluoroquinolone,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
2,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_19,FRICKE_19A,FRICKE_19B,Pre Post-ABx,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
set(abund_wide.index).intersection(set(pod_meta["Name"]))

{'PT_19_0010D62',
 'MET241',
 'TF28_BL',
 'FDM037W24',
 'SGP007602',
 'PT_19_0006D_22',
 'MET46',
 'PT_18_0018D56',
 'TF49_26wk',
 'MET156',
 'Ge_D1',
 'PM.CDonor',
 'Ge_R5.V2',
 'PAUL.case3_after',
 'FDM048W0',
 '1_22_W6',
 'PT_19_0007D67',
 'PT_18_0018D383',
 'Pa_R14.V0',
 'MET179',
 'FRICKE_28A',
 'MET160',
 'MET88',
 'FDM061W0',
 'Ge_R6.V4',
 '1_17_W2',
 'Pa_R5.V4',
 'FDM041W24',
 'SGP007162',
 'PT_19_0024D48',
 'FDM053W16',
 'P20_P28_P25.CDonor',
 'Ut_R5.V2',
 'DM08_D2',
 'SGP007636',
 'FRICKE_9A',
 'DA_R04_UC_P_07_POST',
 'SGP007613',
 'MET212',
 'MET249',
 'BOURSI_R10.D31',
 'SGP007185',
 'PT_19_0009D32',
 'PT_18_0018D133',
 'MET4',
 'MET177',
 'Ge_R13.V5',
 'PT_18_0018D21',
 'TF19_6WK',
 'PT_19_0010D47',
 '1_17_W10',
 'MET273',
 'SGP007160',
 'PT_19_0013D90',
 'TF19_BL',
 'DB_R02_CDI_C_02_PRE',
 'P30_P31_P17.CDonor',
 'SGP007172',
 'MET41',
 'MET276',
 'BOURSI_R3.D0',
 'Ge_R8.V3',
 'PT_19_0007D57',
 'TF03_6wk',
 'SGP007166',
 'Ut_R4.V4',
 'FMT56',
 'TF13_BL',
 'DF14_D3',
 'FAT_DON_11_22_0_5',
 'MET60',
 'Ge_R8.V4',
 'BOURSI_R7.D7',
 'PT_19_0013D33',
 'PT_19_0024D83',
 'SGP007663',
 'Ge_R2.V2',
 'BOURSI_R5.D7',
 'MET218',
 'FMT4',
 'SGP007184',
 'MET92',
 'FDM012W0',
 'SGP007642',
 'SGP007206',
 'SGP007666',
 'TM04_26wk',
 'FMT43',
 'DF17_D7',
 'PT_19_0002D99',
 'FMT_18_0007',
 '1_1_W24',
 'MET205',
 'MET207',
 'MET267',
 'PAUL.donor_5',
 'FDM010W16',
 'Ge_R6.V2',
 'DM07_D6',
 'PT_19_0002D29',
 'FDM040W16',
 'DB_D_13',
 'D4_S280',
 'PT_19_0001D56',
 'FMT44',
 'PT_18_0018D_23',
 'FRICKE_20E',
 'FDM035W4',
 'TM17_26wk',
 'FRICKE_54B',
 'PT_19_0010D78',
 'PT_19_0024D34',
 'FDM009W24',
 'DB_R03_CDI_P_04_POST',
 'DA_D_15',
 'TF34_26wk',
 'FDM028W4',
 'MET282',
 'FRICKE_29A',
 'PT_19_0007D14',
 '1_1_W6',
 'TM10_6wk',
 'PT_18_0032D_22',
 'PT_19_0002D42',
 'TF39_6wk',
 'PAUL.case12_after',
 'TM17_12wk',
 'TM04_12wk',
 'DM07_D3',
 'male_4',
 'Ge_R13.V2',
 'FDM017W0',
 'SGP007660',
 'TM17_BL',
 'SGP007644',
 'DB_R02_CDI_C_04_POST',
 '1_19_W14',
 'TM14_6wk',
 'PT_18_0018D75',
 'DF16_D2',
 'TF22_BL',
 'FDM022W16',
 'MET274',
 '1_22_W10',
 'Ge_R1.V5',
 'DA_R04_UC_P_03_POST',
 'FMT_19_0008',
 'FMT66',
 'PT_19_0006D19',
 'MET181',
 'female_8',
 'MET175',
 'SGP007173',
 'PT_19_0026D7',
 'SGP007212',
 'PT_19_0006D55',
 'FAT_DON_11_22_0_6',
 'PT_19_0024D28',
 'SGP007213',
 'SGP007650',
 'PT_18_0018D424',
 '1_4_W10',
 'DB_R05_UC_P_04_POST',
 'PAUL.donor_4',
 'BOURSI_R1.D65',
 'SGP007616',
 'MET227',
 'FAT_DON_19_22_0_0',
 '1_22_D0',
 'MET7',
 'TF23_BL',
 'SGP007152',
 'MET150',
 'TM14_BL',
 'SGP007163',
 'MET281',
 'PAUL.case7_after',
 'SGP007646',
 'DB_R02_CDI_C_03_POST',
 'SGP007678',
 'MET27',
 'PT_18_0018D47',
 'PT_19_0009D18',
 'PT_18_0007D85',
 '1_19_D0',
 'FAT_012_22_42_0',
 'FDM008W0',
 'MET191',
 'DM07_D1',
 'DM08_D3',
 'MET155',
 'FDM013W0',
 'FDM050W4',
 'FRICKE_16D',
 'TF20_12wk',
 'PAUL.case13_after',
 'Ut_R2.V4',
 'FMT30',
 'Ge_R8.V0',
 'FDM024W24',
 'FDM001W4',
 'DA_R05_UC_C_05_POST',
 'MET87',
 'MET223',
 'MET22',
 'TM05_6wk',
 'FDM010W0',
 'DM05_D1',
 'P33_P1_P29.CDonor',
 'MET64',
 'FMT55',
 'DB_R01_CDI_C_07_POST',
 'TF29_26wk',
 'PT_19_0013D61',
 'MET246',
 'BOURSI_R7.D31',
 'MET100',
 'Pa_R2.V0',
 'BOURSI_R6.D7',
 'TF11_26wk',
 'TM34_26wk',
 'Ge_R2.V3',
 'FMT27',
 'TF29_BL',
 'SGP007167',
 'SGP007155',
 'FDM053W4',
 'male_5',
 'PT_19_0002D50',
 'MET225',
 'PT_19_0002D183',
 'FDM055W16',
 'MET56',
 'SGP007599',
 'MET162',
 'FDM046W4',
 'DF17b_D2',
 'TM14_12wk',
 'MET48',
 'Ge_R11.V5',
 'MET3',
 'SGP007671',
 'PT_18_0018D496',
 'TF01_12wk',
 'Ge_R13.V0',
 'FDM030W16',
 'SGP007592',
 'Pa_R14.V4',
 '7_2_D1',
 'PI.CDonor',
 'FDM031W24',
 'MET221',
 'MET269',
 'MET151',
 'MET74',
 'BOURSI_R4.D65',
 'MET52',
 'MET170',
 '1_9_W10',
 'FDM017W4',
 'MET57',
 'PT_19_0002D92',
 'PT_19_0002D211',
 'Ge_D7_1',
 'PAUL.case11_after',
 'SGP007637',
 'PT_19_0002D120',
 'MET145',
 'DA_R01_CDI_P_03_POST',
 'D9_BhdST013',
 'MET81',
 'SGP007614',
 'MET77',
 'TF13_26wk',
 'MET174',
 'TM28_BL',
 'MET127',
 'MET213',
 'FRICKE_18A',
 'TF43_12wk',
 'FDM028W0',
 'FDM035W24',
 'SGP007600',
 'DM12_D3',
 'TM18_26wk',
 'PAUL.donor_1',
 'FDM050W16',
 'FMT106',
 'MET265',
 'MET16',
 'MET20',
 'FMT18',
 'PT_18_0018D528',
 'SGP007623',
 'SGP007198',
 'CHANDONOR',
 'DA_R01_CDI_P_05_POST',
 'PT_19_0010D68',
 'TF34_BL',
 'PT_18_0018D466',
 'FDM040W4',
 '1_15_D0',
 'PAUL.case5_before',
 'SGP007655',
 'MET139',
 'TF01_26wk',
 'TM10_26wk',
 'MET165',
 'MET284',
 'MET275',
 'P4_P35_P18.CDonor',
 'MET2',
 'PT_19_0024D7',
 'PT_19_0009D_24',
 'TM21_BL',
 'PAUL.case12_before',
 '1_15_W2',
 'SGP007594',
 'MET132',
 'TM34_6wk',
 'FMT69',
 'PT_19_0001D_29',
 'SGP007651',
 'PT_19_0002D57',
 'FDM001W0',
 'MET11',
 'MET245',
 'Pa_R5.V0',
 'PT_19_0024D77',
 'TM14_26wk',
 'MET99',
 'TM05_26wk',
 'FDM026W24',
 'MET13',
 'MET208',
 'MET242',
 'FMT_19_0002',
 'MET172',
 'FAT_006_22_84_0',
 '1_17_D0',
 'SGP007662',
 'PT_19_0002D_7',
 'MET49',
 'DB_R01_CDI_C_05_POST',
 'SGP007673',
 'TM21_26wk',
 'FDM017W24',
 'Pa_R14.V2',
 'DF17_D5',
 'TM29_BL',
 'FMT101',
 'FDM022W0',
 'MET220',
 '1_22_W2',
 'PAUL.case5_after',
 'PT_19_0010D146',
 'PT_19_0010D14',
 'SGP007168',
 'PT_18_0018D29',
 'MET93',
 'TF35_12wk',
 'MET66',
 'Ge_D4',
 'TM04_BL',
 'Pa_R3.V0',
 'PT_19_0001D21',
 'MET187',
 'Ut_R4.V2',
 'DF16a_D4',
 'MET133',
 'MET108',
 'Pa_R2.V4',
 'SGP007153',
 'TF30_BL',
 'MET239',
 'SGP007608',
 'PT_19_0006D47',
 'FDM020W16',
 'BOURSI_Donor1.D0',
 'FMT_18_0024',
 'MET211',
 'FDM008W16',
 'PT_19_0013D_21',
 'MET219',
 'MET109',
 'SGP007216',
 'DB_R05_UC_P_05_POST',
 'MET228',
 'Ge_R8.V2',
 'TF36_BL',
 '1_19_W6',
 'SGP007647',
 'FDM060W4',
 'FRICKE_23G',
 'FMT11',
 'DA_R04_UC_P_02_PRE',
 'PT_19_0010D55',
 '7_2_D2',
 'TF01_6wk',
 'FAT_DON_11_22_0_N',
 'DM03_D4',
 'PT_18_0032D22',
 'TF38_BL',
 'PE.CDonor',
 'DB_R05_UC_P_01_PRE',
 'FDM034W0',
 'TF28_12wk',
 'DA_R02_CDI_C_07_POST',
 'Ge_R14.V2',
 'MET194',
 'MET17',
 'SGP007180',
 'SGP007596',
 'MET136',
 'MET259',
 'SGP007661',
 'TF08_BL',
 'TM18_6wk',
 'Ut_R2.V5',
 'TF16_BL',
 'BOURSI_R6.D0',
 'TF42_6wk',
 'PAUL.case15_before',
 'FMT39',
 'FDM053W24',
 'MET106',
 'FDM061W24',
 'FAT_015_22_84_0',
 'TM11_BL',
 'Pa_R5.V5',
 'DA_D_08',
 'MET216',
 'FDM006W16',
 'PAUL.case4_after',
 'FDM048W4',
 'FDM043W0',
 'PT_19_0023D13',
 'PT_18_0034D27',
 'SGP007174',
 'MET121',
 'MET36',
 'PT_18_0007D101',
 'FMT_19_0005',
 'MET164',
 'DM12_D6',
 'Ge_R5.V3',
 'FDM055W0',
 'FDM035W16',
 'MET184',
 'MET178',
 'PAUL.case4_before',
 'SGP007211',
 'SGP007676',
 'SGP007169',
 'TF43_6wk',
 'FDM050W0',
 'MET193',
 'PT_19_0013D55',
 'FDM060W16',
 'PT_19_0010D12',
 'Ge_D3',
 'PAUL.case1_after',
 'FMT92',
 'MET163',
 'SGP007675',
 'MET124',
 'MET130',
 'PT_18_0007D514',
 'PT_18_0033D_23',
 'FRICKE_18B',
 'MET256',
 'FDM059W4',
 'SGP007186',
 'FAT_008_22_0_0',
 'TF10_12wk',
 'DB_R01_CDI_C_02_PRE',
 'MET144',
 'PT_19_0002D85',
 'MET233',
 'TM02_6WK',
 'FAT_008_22_84_0',
 'TF19_26wk',
 'SGP007657',
 'FDM020W0',
 'PT_18_0007D471',
 'FMT96',
 'SGP007624',
 'TF16_12wk',
 'Pa_R3.V3',
 'female_7',
 'TF20_6WK',
 'MET215',
 'FMT99',
 'TM02_BL',
 'BOURSI_R3.D7',
 '1_4_W6',
 'BOURSI_R4.D0',
 'FDM048W24',
 'PT_18_0018D490',
 'MET61',
 'FDM040W0',
 'PT_19_0010D97',
 'FDM004W16',
 'SGP007207',
 'BOURSI_R10.D7',
 'BOURSI_R7.D65',
 'SGP007215',
 'BOURSI_R1.D0',
 'MET202',
 'DA_R05_UC_C_03_POST',
 'MET226',
 'DB_R03_CDI_P_05_POST',
 'SGP007148',
 'DB_R01_CDI_C_06_POST',
 '1_1_W14',
 'PT_19_0024D92',
 'SGP007170',
 'TF16_6wk',
 'MET107',
 'SGP007649',
 'FDM008W24',
 'MET131',
 'DF17_D3',
 'PAUL.case15_after',
 'FAT_006_22_0_0',
 'PT_19_0002D114',
 'SGP007617',
 'BOURSI_R2.D31',
 'DF16_D9',
 'MET169',
 'PK.CDonor',
 'SGP007668',
 'TF10_BL',
 'FDM009W0',
 'DA_D_09',
 'female_3',
 'MET122',
 'FMT67',
 'FRICKE_23A',
 'SGP007667',
 'MET272',
 'SGP007194',
 'FAT_015_22_14_0',
 'FMT_18_0030',
 'MET161',
 'MET279',
 'DM03_D1',
 'FAT_006_22_42_0',
 'FDM017W16',
 'SGP007193',
 'Ut_R5.V4',
 'PT_19_0010D139',
 'FMT41',
 'BOURSI_R8.D31',
 'SGP007606',
 'BOURSI_R3.D65',
 'PT_19_0013D40',
 'DF12_D2',
 'DF16_D3',
 'MET110',
 'TM29_12wk',
 'MET79',
 'FMT50',
 'MET114',
 'SGP007195',
 'FDM037W0',
 'TF46_6wk',
 'MET72',
 'SGP007191',
 'PT_19_0024D62',
 'SGP007597',
 'MET25',
 'female_4',
 'FDM046W16',
 'TM01_26wk',
 'FMT12',
 'P19_P13_P11.CDonor',
 'SGP007632',
 'FDM060W24',
 'Ge_D7_2',
 'PT_18_0018D432',
 'MET262',
 'Ge_R11.V0',
 'DF16_D6',
 'SGP007611',
 'PT_18_0018D440',
 'PAUL.case8_after',
 'MET270',
 'FAT_020_22_42_0',
 'SGP007165',
 'PT_19_0010D123',
 'MET44',
 'DB_R01_CDI_C_04_POST',
 'SGP007149',
 'MET135',
 'DM08_D6',
 'D16_BhdST0634',
 'MET117',
 'DM12_D2',
 'PT_18_0034D146',
 'PT_19_0010D104',
 'MET264',
 'DF14_D2',
 'PT_18_0034D20',
 'BOURSI_R8.D7',
 'Ge_R6.V3',
 'MET28',
 'MET271',
 'MET47',
 'TF11_BL',
 'MET128',
 'PAUL.case11_before',
 'SGP007634',
 'TF46_BL',
 'DB_R04_CDI_P_04_POST',
 'TF11_12wk',
 'Pa_R3.V4',
 'PT_19_0007D35',
 'PT_19_0007D45',
 'FDM010W4',
 'DM07_D4',
 'FAT_020_22_14_0',
 'TF28_26wk',
 'DF17_D4',
 'MET250',
 'BOURSI_R2.D65',
 'PT_18_0018D503',
 'TF38_12wk',
 'MET238',
 'Ge_R13.V3',
 'SGP007605',
 'PT_18_0018D42',
 'PT_19_0010D124',
 'TF46_12wk',
 'PAUL.donor_3',
 'TF10_6wk',
 'PT_18_0007D174',
 'FDM013W16',
 'FDM042W24',
 '1_15_W10',
 'PT_19_0002D141',
 'FDM055W4',
 'MET38',
 'FDM031W0',
 'PT_19_0002D16',
 'PT_18_0007D41',
 'P24_P9_P3.CDonor',
 'Ut_D18',
 'PT_19_0007D21',
 'DA_R04_UC_P_04_POST',
 'MET103',
 'MET85',
 'MET142',
 'MET231',
 'TF08_6wk',
 'TF22_12wk',
 'SGP007150',
 'SGP007677',
 'FDM001W24',
 'BOURSI_R4.D7',
 'DM08_D5',
 'TF03_26wk',
 'TM28_26wk',
 'TM19_BL',
 'FRICKE_20B',
 'FDM020W24',
 'FDM059W24',
 'FDM024W4',
 'FDM030W4',
 'FDM055W24',
 'male_1',
 'PT_19_0001D30',
 'FRICKE_18C',
 'FDM025W16',
 'TM02_26wk',
 'FDM024W0',
 'BOURSI_R10.D65',
 'PT_18_0007D267',
 'SGP007202',
 'TF49_12wk',
 'Ge_R5.V0',
 'FDM059W16',
 'FRICKE_29B',
 'Ta_R1.V0',
 'PAUL.donor_2',
 'MET14',
 'FMT81',
 'FRICKE_19A',
 'DM12_D5',
 'MET123',
 'PT_19_0002D64',
 'MET285',
 'FMT110',
 'TM01_BL',
 'Ge_R14.V5',
 'MET278',
 'FDM049W0',
 'BOURSI_R2.D7',
 'TF20_BL',
 'Pa_D14',
 'TF21_12wk',
 'MET40',
 'FMT59',
 'MET280',
 'FDM060W0',
 'Ge_R1.V2',
 'PT_18_0034D_22',
 'Ta_R1.V2',
 'Ge_R11.V4',
 'DM08_D4',
 'MET96',
 '1_1_D0',
 'Pa_R2.V3',
 'BOURSI_R6.D31',
 '1_1_W18',
 'MET29',
 'FMT93',
 'PAUL.case6_after',
 'FDM025W24',
 'MET39',
 'TF36_6wk',
 'FMT10',
 '1_9_W14',
 'Ge_R11.V3',
 'DM07_D2',
 'FDM040W24',
 'PAUL.case13_before',
 'TF13_12wk',
 'FDM061W4',
 'MET224',
 'MET82',
 'MET252',
 'PT_19_0009D11',
 'MET84',
 'SGP007187',
 'FRICKE_19C',
 'MET257',
 'SGP007631',
 'TF42_26wk',
 'PT_18_0018D514',
 'PT_18_0018D411',
 'MET230',
 'Ut_R4.V3',
 'DA_R02_CDI_C_02_PRE',
 '7_55',
 'FDM041W0',
 'PT_19_0002D169',
 'MET198',
 'MET141',
 'PT_18_0018D461',
 'TF39_12wk',
 'DA_R05_UC_C_04_POST',
 'TM21_6wk',
 'PT_18_0007D7',
 '1_15_W24',
 'PAUL.donor_6',
 'FDM002W16',
 'FAT_015_22_0_0',
 'male_2',
 'PT_19_0024D_9',
 'PT_19_0007D_28',
 'DA_R01_CDI_P_02_POST',
 'PT_18_0007D21',
 'female_9',
 'TM17_6WK',
 'SGP007146',
 'MET98',
 'PT_19_0002D8',
 'DB_R04_CDI_P_08_POST',
 'TF20_26wk',
 'FMT_19_0009',
 'FDM002W0',
 '1_15_W18',
 'SGP007621',
 'SGP007665',
 'PT_19_0024D56',
 'SGP007638',
 'FAT_012_22_0_0',
 'FMT33',
 'Ge_R1.V0',
 'MET171',
 'DA_R02_CDI_C_06_POST',
 'BOURSI_R2.D0',
 'MET86',
 'TM30_BL',
 'PT_18_0018D96',
 'PT_19_0002D106',
 'DF16_D5',
 'MET260',
 'PT_19_0002D127',
 'MET138',
 'Ut_R4.V0',
 'TM30_26wk',
 'PT_18_0034D48',
 'MET53',
 'TM08_6wk',
 'FAT_008_22_14_0',
 'MET268',
 'FRICKE_9B',
 'PT_18_0007D53',
 'MET168',
 'PT_19_0002D162',
 'TF21_6WK',
 'SGP007154',
 'MET12',
 'DF12_D9',
 'DF14_D6',
 'FMT13',
 'SGP007669',
 '1_9_W6',
 'PT_18_0018D482',
 'FRICKE_28C',
 'TF04_BL',
 'MET263',
 'FDM047W24',
 'MET210',
 'MET83',
 '1_19_W18',
 '7_59',
 'PT_19_0002D190',
 'PT_19_0023D_22',
 'FMT14',
 'DB_D_07',
 'MET55',
 'MET35',
 'PAUL.case2_before',
 'TF42_12wk',
 'FDM043W24',
 'DF14_D9',
 'MET9',
 'MET190',
 'FDM049W16',
 'DA_R02_CDI_C_04_POST',
 'TF35_BL',
 'FRICKE_9E',
 'FAT_DON_11_22_0_4',
 'DA_R04_UC_P_09_POST',
 'TF30_12wk',
 'FDM043W16',
 'MET188',
 'TM21_12wk',
 'SGP007178',
 'FDM004W4',
 'MET186',
 'PAUL.case1_before',
 'FMT37',
 'FMT51',
 'DF14_D4',
 'FMT58',
 '1_9_D0',
 'DB_R04_CDI_P_06_POST',
 'FRICKE_28B',
 'BOURSI_R9.D0',
 'P12_P2_P34.CDonor',
 'SGP007201',
 'SGP007652',
 'DF16b_D4',
 'SGP007641',
 'FDM037W16',
 'DF17_D9',
 'PT_19_0010D89',
 'TF22_26wk',
 'FDM009W16',
 'FMT85',
 'FDM051W0',
 'FDM024W16',
 'FRICKE_16B',
 'DA_R03_CDI_C_06_POST',
 'MET58',
 'MET195',
 'Ge_D6',
 'PT_19_0024D13',
 'FDM042W0',
 'DM03_D6',
 'TF36_26wk',
 'MET244',
 'DF17_D8',
 'FDM002W24',
 'DF14_D5',
 'DB_R04_CDI_P_02_PRE',
 'SGP007659',
 'MET166',
 'DB_D_11',
 'MET30',
 'MET51',
 'MET185',
 'TF11_6wk',
 'SGP007161',
 'Pa_R5.V3',
 'DA_R05_UC_C_01_PRE',
 'DB_R03_CDI_P_02_PRE',
 'FDM041W4',
 'SGP007626',
 'MET111',
 'FDM034W4',
 'MET182',
 'PT_19_0010D_24',
 'FDM049W24',
 'DB_D_08',
 'SGP007591',
 'SGP007607',
 'FDM034W24',
 'SGP007654',
 'MET70',
 'FMT5',
 'BOURSI_R9.D31',
 'PT_18_0018D535',
 'PT_19_0023D29',
 'FDM046W24',
 'PT_19_0010D19',
 'TM10_BL',
 'PAUL.case3_before',
 'TF43_BL',
 'Pa_R5.V2',
 'Pa_D7',
 'FMT_19_0006',
 'TF35_26wk',
 'TF38_6wk',
 'TM34_12wk',
 'FDM010W24',
 'TM10_12wk',
 'FMT103',
 'DB_R02_CDI_C_06_POST',
 'PT_18_0018D69',
 'FDM019W4',
 'TF13_6wk',
 'DF12_D7',
 'SGP007203',
 'TF43_26wk',
 'PT_18_0018D390',
 'SGP007175',
 'P16_P22_P26.CDonor',
 'MET54',
 'MET247',
 'TF29_12wk',
 'DM03_D2',
 'FRICKE_29C',
 'TF28_6wk',
 'PT_19_0024D113',
 'SGP007603',
 'female_6',
 'MET75',
 'BOURSI_R9.D7',
 'DF17_D6',
 'TM08_BL',
 'TF22_6wk',
 'FMT75',
 'FDM034W16',
 'DB_R03_CDI_P_08_POST',
 'MET120',
 'male_6',
 'FMT35',
 'Ge_R1.V4',
 'PT_19_0013D27',
 'FDM047W4',
 'MET80',
 'DB_R05_UC_P_06_POST',
 'MET176',
 'MET203',
 'MET240',
 'SGP007159',
 'Pa_R3.V5',
 'TF10_26wk',
 'DB_R03_CDI_P_07_POST',
 'FDM012W16',
 'TF49_6wk',
 'FMT2',
 'DF17a_D2',
 '1_17_W6',
 'TM28_6wk',
 'SGP007171',
 'MET31',
 'FDM043W4',
 'Ge_R1.V3',
 'FDM019W16',
 'TF21_BL',
 'Pa_D6',
 'FDM031W4',
 'FDM019W0',
 'MET189',
 'TM30_6wk',
 'MET24',
 '1_15_W6',
 'DA_D_10',
 'MET97',
 'PT_18_0018D63',
 'DA_R01_CDI_P_06_POST',
 'PT_19_0007D29',
 'FMT_18_0028',
 'PT_18_0018D473',
 'SGP007674',
 'FMT34',
 'MET23',
 'TF30_6wk',
 'PAUL.case7_before',
 'Ge_R14.V0',
 'DB_D_14',
 'MET26',
 'MET235',
 'MET266',
 ...}

In [18]:
pod_meta = pod_meta[pod_meta["Manuscript"].str.contains("Podlesny", na=False)]

In [19]:
pod_meta["Name"].head()

0    FRICKE_16A
1    FRICKE_18A
2    FRICKE_19A
3    FRICKE_20A
4    FRICKE_23A
Name: Name, dtype: object

In [20]:
set(abund_wide.index).intersection(set(pod_meta["Name"]))

{'FRICKE_16A',
 'FRICKE_16B',
 'FRICKE_16D',
 'FRICKE_18A',
 'FRICKE_18B',
 'FRICKE_18C',
 'FRICKE_19A',
 'FRICKE_19B',
 'FRICKE_19C',
 'FRICKE_19G',
 'FRICKE_20A',
 'FRICKE_20B',
 'FRICKE_20E',
 'FRICKE_23A',
 'FRICKE_23B',
 'FRICKE_23C',
 'FRICKE_23G',
 'FRICKE_28A',
 'FRICKE_28B',
 'FRICKE_28C',
 'FRICKE_29A',
 'FRICKE_29B',
 'FRICKE_29C',
 'FRICKE_29I',
 'FRICKE_54A',
 'FRICKE_54B',
 'FRICKE_54C',
 'FRICKE_9A',
 'FRICKE_9B',
 'FRICKE_9E'}

In [21]:
common = list(set(abund_wide.index).intersection(set(pod_meta["Name"])))

In [22]:
abund_wide = abund_wide.loc[common]

In [23]:
pod_meta = pod_meta[pod_meta["Name"].isin(common)]

In [24]:
pod_meta = pod_meta.set_index("Name").loc[abund_wide.index]

In [25]:
print(abund_wide.shape)
print(pod_meta.shape)

(30, 860)
(30, 19)

In [26]:
pod_meta.columns

Index(['Manuscript', 'Study', 'Disease_Group', 'Disease', 'Case_Name',
       'Donor.Name', 'Sample_Type', 'Days_Since_FMT', 'Case_ABx', 'ABx_days',
       'ABx_PostFMT', 'Lavage', 'FMT_route', 'FMT_rounds', 'Colonoscopy_n',
       'Nasogastric_n', 'Gastroduodenal_n', 'Enema_n', 'Pill_n'],
      dtype='object')

In [27]:
pod_meta.head()

,Manuscript,Study,Disease_Group,Disease,Case_Name,Donor.Name,Sample_Type,Days_Since_FMT,Case_ABx,ABx_days,ABx_PostFMT,Lavage,FMT_route,FMT_rounds,Colonoscopy_n,Nasogastric_n,Gastroduodenal_n,Enema_n,Pill_n
Name,,,,,,,,,,,,,,,,,,,
FRICKE_16D,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_16,FRICKE_16B,Post,365.0,NaN,0.0,0.0,1.0,Colonoscopy,1.0,1.0,0.0,0.0,0.0,0.0
FRICKE_29I,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_29,FRICKE_29B,Post,28.0,NaN,0.0,0.0,1.0,Colonoscopy,1.0,1.0,0.0,0.0,0.0,0.0
FRICKE_23A,Podlesny et al.,FRI,rCDI,rCDI,FRICKE_Case_23,FRICKE_23B,Pre Post-ABx,0.0,lincosamide,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
FRICKE_23B,Podlesny et al.,FRI,rCDI,NaN,NaN,NaN,Donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FRICKE_29B,Podlesny et al.,FRI,rCDI,NaN,NaN,NaN,Donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
post_meta = pod_meta[pod_meta["Sample_Type"] == "Post"].copy()

In [31]:
post_meta["response"] = post_meta["Days_Since_FMT"] > 30

In [32]:
print(post_meta["response"].value_counts())

response
True     7
False    5
Name: count, dtype: int64

In [33]:
x = abund_wide.loc[post_meta.index]

In [34]:
y = post_meta["response"]

In [35]:
print(x.shape)
print(y.shape)

(12, 860)
(12,)

In [36]:
x.to_csv("../data/processed/x_post.csv")
y.to_csv("../data/processed/y_post.csv")